### PR TITLE
ISSD-2681 Add Keyboard shortcut "/ " to activate search bar for quick search

### PR DESCRIPTION
**Pull request by rtienpal**

### CODE REVIEW

**Comment by rtienpal** [comment]
ci:test:sf

**Comment by rtienpal** [comment]
I deployed to test it, and for some reason it was not working (was working 2 weeks ago), checking to see the problem

**Comment by ryanschuhler** [comment]
Hey @rtienpal, for this I think the code would be easier to find and more maintainable if we add the hotkey logic to the public site navigation fragment (since we ended up saying all '/' hotkey events open the main site search)
Can you move the logic into [this file ](https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/fragments/group/liferay-learn/fragments/public-sites-navigation/index.js#L103-L105) so it calls the changeFocus function? 
Thanks!

**Comment by rtienpal** [comment]
Hey @ryanschuhler changes made, I used ternary to changefocus if the searchbar was already opened, or click the button that triggers the searchbar and already changes focus to the searchbar

**Pull request closed without merging**
